src/shared.rs

Small edit to impl `Error` for `HyprError`, this lets you use it together with crates like `anyhow`, for example:
```rs
fn main() -> anyhow::Result<()> {
let workspaces = Workspaces::get()?;
dbg!(workspaces);
Ok(())
}
```

Implement `Error` for `HyprError`

---

src/data/macros.rs
src/data/regular.rs

There's no need to move/clone data anymore if there's no reason to do so, I tested the code on my own application: https://github.com/tukanoidd/hyprr, it compiles and works like a charm
No breaking changes, macro functionality was just extended
I didn't add anything to the "p" variant because it didn't seem to be used anywhere.

Added iter functions to data structures

---

src/shared.rs

Without this fix, when I got a lot of windows open / clients, this lead to a truncated JSON.
fix: https://github.com/cyrinux/hyprland-autoname-workspaces/issues/8

fix: read all Hyprland socket data returned

---

src/data/regular.rs

It Looks like in recent hyprland, client struct change. Some data are now a i8. 
fix: https://github.com/cyrinux/hyprland-autoname-workspaces/issues/17

fix: client struct use more signed integer

---

src/data/regular.rs

* grouped take a Vec<Box<Address>>
* and looks like monitor can be -1 now
* in prevention, we will allow fullscreenmode to be negative too
fix: https://github.com/cyrinux/hyprland-autoname-workspaces/issues/21

fix: some others Client struct fixes, this fix grouped mode and monitor

---

src/data/regular.rs

Fix crash in dwindle mode https://github.com/cyrinux/hyprland-autoname-workspaces/issues/37
We have maybe more u16 and u32 to convert like this but I'm shy to transform them all...
Can you please make a release then 🙏🏻

fix: client size u16 to i16

---

src/event_listener/shared.rs

this fix the urgent event
fix: https://github.com/hyprland-community/hyprland-rs/issues/44
note: I deduct the new place of the screencopy event but I was not able to test it.

fix: this fix the urgent event

---

src/config.rs
src/ctl.rs
src/data/regular.rs
src/dispatch.rs
src/keyword.rs
src/shared.rs

We mimic the hyprctl behavior with prepending a slash before the command.
https://github.com/hyprwm/Hyprland/blob/da093a8aec7d3e5030f7ef4b0813f1d8160f47f5/hyprctl/main.cpp#L321
https://github.com/hyprwm/Hyprland/blob/da093a8aec7d3e5030f7ef4b0813f1d8160f47f5/hyprctl/main.cpp#L204
https://github.com/hyprwm/Hyprland/blob/da093a8aec7d3e5030f7ef4b0813f1d8160f47f5/hyprctl/main.cpp#L185
Note that cargo test pass, but maybe its not a full coverage.
fix: https://github.com/cyrinux/hyprland-autoname-workspaces/issues/41
All credit to @maximbaz ❤️

fix: allow passing slash in (dispatcher) commands

---

src/dispatch.rs

~this PR just adds movecursor dispatch, and cursor_pos ctl~
~I'm using `unwrap()` while parsing the position from `cursor_pos`, just because I'm not sure how you want it exactly~
~I could add a new variant to the error type or just `expect()` it if you don't want that `unwrap()`~
this PR just adds movecursor dispatch

add movecursor dispatch

---

src/data/regular.rs

This PR contains a fix for the following bug: When retrieving the active window, parsing fails with
```
SerdeError(
Error("data did not match any variant of untagged enum Aux", line: 0, column: 0),
)
```
Here is an example of the data that triggers this error:
```
{
"address": "0x898d4ec0",
"mapped": true,
"hidden": false,
"at": [13, 13],
"size": [939, 497],
"workspace": {
"id": 1,
"name": "1"
},
"floating": false,
"monitor": 0,
"class": "org.gnome.SoundRecorder",
"title": "Tonaufzeichner",
"initialClass": "org.gnome.SoundRecorder",
"initialTitle": "Tonaufzeichner",
"pid": 328198,
"xwayland": false,
"pinned": false,
"fullscreen": false,
"fullscreenMode": 0,
"fakeFullscreen": false,
"grouped": [],
"swallowing": "0x898b4540"
}
```
Given that the field `swallowing` does not contain a …

Fix parsing error when swallowing is active

---

src/event_listener/shared.rs

Since Regex [updated](https://github.com/rust-lang/regex/commit/ff27ce08bcc7957dbe3a4ada5cf0eb9b1d80ba13#diff-97e25e2a0e41c578875856e97b659be2719a65227c104b992e3144efa000c35e) their code for error we need to update the code.

Remove reference to RegexError::__Nonexhaustive

---

src/event_listener/shared.rs

Wrong ordering of events parsing introduced when fixing urgent event bug in the commit f05a30076c7d06ed9876309868e91dae88c9bce1.
This should fix https://github.com/hyprland-community/hyprland-autoname-workspaces/issues/82

fix: reorder minimize and screencast

---

src/event_listener/shared.rs

Fixes #65
With this change, the examples I mention in that issue are now:
```
Some(
WindowEventData {
window_class: "firefox",
window_title: "GrapheneOS: first impressions, stumbling blocks, and opinions - YouTube — M
ozilla Firefox",
window_address: Address(
"597b290",
),
},
)
```
and
```
Some(
WindowEventData {
window_class: "firefox",
window_title: "hyprland-community/hyprland-rs: An unofficial rust wrapper for hyprland's I
PC [maintainers=@yavko,@cyrinux] — Mozilla Firefox",
window_address: Address(
"597b290",
),
},
)
```

fix: make class capture group lazy

---

src/shared.rs

Should allow `WorkspaceType` to be used inside `HashMap`s now.
@yavko

WorkspaceType: implement Hash

---

src/dispatch.rs

Fixes #82 
hyprctl expects window addresses to be formatted as `0xDEADBEEF` instead of simply `DEADBEEF`.

fix: window address string formatting

---

src/dispatch.rs
src/event_listener/shared.rs

#85 actually created issues with data returned from data commands.
The issue stems from the fact that data commands are calling hyprctl with the `--json` flag enabled. hyprctl returns addresses formatted as `0xDEADBEEF` from JSON, but does not do the same with regular output.
Addresses in events are returned as `DEADBEEF` instead, so this causes inconsistencies in the data when it comes from data commands and when it comes from events.
This PR addresses this issue by sticking with the `0xDEADBEEF` format, as that's the format dispatchers are expecting for window addresses. In every event listener where we are parsing window addresses, I simply prepended the matched address with `0x` in a helper function.

fix: make address parsing consistent between events and data commands

---

src/data/regular.rs

XWayland windows like to do this weird behavior, where their monitor ids are completely messed up:
```
Window 55b38ee739a0 -> :
...
monitor: 18446744073709551615
...
```
This monitor id unfortunately doesn't fit in i64, causing this Serde error:
`Error: SerdeError(Error("invalid value: integer '18446744073709551615', expected i64", line: 12, column: 35))`
when doing
`Clients::get()?.to_vec()`.
Reference to the huge number in the monitor id can be found in this issue: https://github.com/hyprwm/Hyprland/issues/3357#issue-1899878576
which references this issue( https://github.com/hyprwm/Hyprland/issues/3357#issuecomment-1722540643 ), where it's said to be common xwayland/x11 behavior:
https://github.com/hyprwm/Hyprland/issues/2597#issuecomment-1611220191

Fix monitor ids (again)

---

src/data/regular.rs

Useful for performing keyboard layout changes programmatically, for example. 
See https://github.com/hyprwm/Hyprland/blob/4a4e13f8acedd2dc44236deed13fd47096cbe508/src/debug/HyprCtl.cpp#L448

add main to struct Keyboard

---

src/dispatch.rs

This PR:
- adds a `RelativeMonitorIncludingEmpty` variant for `WorkspaceIdentifier(WithSpecial)`, which corresponds to the relative workspace address format with the `r` prefix
https://wiki.hyprland.org/Configuring/Dispatchers/#workspaces
- fixes the doc comment for the `RelativeMonitor` variant

Add WorkspaceIdentifier(WithSpecial) variant for `r` prefix

---

src/shared.rs

removes the need to .to_string() every time two addresses are compared

derive Eq, PartialEq, Hash, Ord, PartialOrd for Address

---

src/data/regular.rs
src/lib.rs
src/shared.rs

Add the `monitorID` field to `Workspaces` since it's provided by hyprctl. 
There's also a deleted line in lib.rs which was edited by `cargo fmt`

Add monitor id to workspaces

---

src/data/regular.rs
src/dispatch.rs
src/shared.rs

The id in the Monitor struct is currently i128, and the monitor field inside client is also i128. [Discussed in this Issue](https://github.com/hyprland-community/hyprland-rs/issues/124).

Use type MonitorId everywhere instead of u8, i128

---

src/event_listener/shared.rs

I found a bug, which happens when the `abuf` contains more than one element and the `to_remove` vector also has more than one index. When deletes first element, the other elements on the right shifts to left, so it will be cause of wrong deletion of element from abuf.
I use `swap_remove`, because the order of elements in `abuf` is not important as far as I know. So the deletion of element will be completed in `O(1)` time (i.e. constant time).

fix: modified logic to_remove indices

---

src/data/macros.rs
src/data/regular.rs
src/event_listener/mutable.rs

- Added `IntoIterator` implementations (consuming, by reference and by mutable reference);
- Added `iter()` and `iter_mut()` (also `into_keys()` and `into_values()` for HashMap types);
- Added macros `implement_iterator!()`;
- Refactored macros `create_data_struct!()` for greater readability and comprehension.
It can break backward compatibility for applications, which uses all `Iterator` functions directly. For example:
```rust
let monitors = Monitors::get()?;
// It won't works.
// let _ = monitors.find(|monitor| monitor.focused);
// But the line below works fine.
let _ = monitors.into_iter().find(|monitor| monitor.focused);
```
Motivation? The type can't be both data struct and `Iterator` at the same time, because it is very strange for me.

feat: added a bunch iterators for data structs

---

src/event_listener/shared.rs

as i understand it, the callback to [add_active_window_change_handler](https://docs.rs/hyprland/latest/hyprland/event_listener/struct.EventListener.html#method.add_active_window_change_handler) receives a `Option<WindowEventData>`. which suggests it should be `None` when no window is active.
after a bunch of debugging, i found [this check](https://github.com/hyprland-community/hyprland-rs/blob/8c9e955fad489aa9d3e49995e89407752c7e39be/src/event_listener/shared.rs#L870), which should be done before formatting the address.

fix: incorrect ActiveWindowChangedV2 address

---

hyprland-macros/Cargo.toml

To allow [Crates.io](https://crates.io/) , [lib.rs](https://lib.rs/) and the [Rust Digger](https://rust-digger.code-maven.com/) to link to it. See also [the manifest](https://doc.rust-lang.org/cargo/reference/manifest.html#the-repository-field).

Add repository field

---

src/event_listener/async_im.rs
src/event_listener/immutable.rs
src/event_listener/mod.rs
src/event_listener/shared.rs
src/shared.rs

Adds a new `add_workspace_destroyed_v2_handler` method to listen to the v2 destroy event. This allows for tracking removal using workspace IDs instead of just their names.
In its current state this isn't perfect but I'm running up against some potential limits of the macros. 
The main issue here is inconsistency with method names:
- The v1 method is `workspace_destroy` while the new one is `workspace_destroyed`
- Elsewhere, where two versions exist, the v1 copy uses the v1 suffix explicitly. Here it's omitted, and only v2 objects are suffixed.
Thought I'd check in before making any decisions on these myself. Let me know what you think the best course of action is here?

feat(event listener): add `removeworkspacev2` event

---

src/dispatch.rs

According to the [latest hyprland documentation](
https://wiki.hyprland.org/Configuring/Dispatchers/), the type of SwapWindow has been modified in DispatchType and SwapNext has been added.
If any modifications are needed, please let me know.

Add SwapNext and update SwapWindow type in DispatchType

---

src/event_listener/async_im.rs
src/event_listener/immutable.rs
src/event_listener/macros.rs
src/event_listener/mod.rs
src/event_listener/mutable.rs
src/event_listener/shared.rs

@yavko rebase on master after you merge this please

feat: implement configreloaded event

---

src/data/regular.rs

Fixes #253 
In the output of `hyprctl -j devices`, `.tablets[].belongsTo` is an object, which we try to deserialize into the `TabletBelongsTo` enum. However, this JSON object is just a "flat" object, containing the fields of one of the enum variants, without a tag specifying which variant it is. So we must use `#[serde(untagged)]` to correctly deserialize it
---
edit: technically there *is* a tag: the `type` field in the parent object:
```
{
"address": "0x627fa3b386f0",
"type": "tabletPad",                     <--
"belongsTo": {
"address": "0x0",
"name": ""
}
},
```
Lmk if this solution is acceptable or if should instead take that `type` field into account (practically I don't think there's a difference)

Fix TabletBelongsTo deserialization

---

src/event_listener/stream.rs

As discussed in #284, add `+ Send` in the trait object owned by `EventStream` in order to allow its use when spawning new async tasks.

Make `EventStream` `Send`

---

Cargo.lock
src/data/regular.rs
src/event_listener/shared.rs

Basically what @chmanie mentioned [here](https://github.com/hyprland-community/hyprland-rs/issues/297#issuecomment-2568587739)
I haven't used `hyprland-rs` yet so some testing is needed by people with actual experience ;)

Fix null monitors causing panics

---

src/dispatch.rs

In hyprland 0.46.0, usage of std::regex was replaced with re2, and as an (unintended?) side effect, the "class:" prefix has become mandatory when matching windows by class name regex
https://github.com/hyprwm/Hyprland/pull/8736
https://github.com/hyprwm/Hyprland/pull/8736/files#diff-3c089c6c6b23a85ab5b4cffb002e8880ad069c8a8b3462f7aafa9e5345c0333dL2395-R2397

add "class:" prefix to class regex window identifier

---

examples/bind.rs
examples/data.rs
examples/data_async.rs
examples/events.rs
examples/events_async.rs
src/config.rs
src/data/mod.rs
src/dispatch.rs
src/event_listener/async_im.rs
src/event_listener/immutable.rs
src/event_listener/macros.rs
src/event_listener/shared.rs
src/event_listener/stream.rs
src/keyword.rs

Some context to the changes: I am also adding support for hyprpaper IPC, but a lot of stuff was not working properly so I could not run `cargo test` without knowing what I might have broken.
This has a bit of overlap with #303 but I thought that I might as well fix all the things that I ran into. The only thing that I am not certain about is the same question as in that PR, whether the `/` should be there in the test or not.
---
Happy to split into more PR's if necessary, but reviewing by commit should hopefully be easy enough!

fix: tests, docs, examples, clippy

---

src/hyprpaper.rs

Fixes #329
Updates the sync `hyprpaper` function to use the hyprpaper socket so it no longer returns "unknown request".

Fix hyprpaper sync to use Hyprpaper socket

---

src/dispatch.rs

Add a `TogglePinWindow` DispatchType that takes a `WindowIdentifier` to pin a specific window.
fixes #146

feat(dispatch): add `pin` with a specified window

---

hyprland-macros/src/lib.rs

chore: deprecate `async_closure` macro

---

src/dispatch.rs

This PR adds the rest of the `layoutmsg` dispatchers, this time for the dwindle layout.

feat: added dwindle layout dispatchers

---

src/dispatch.rs

This PR adds the missing variants for the `WindowIdentifier` and `Position` params.

feat: added missing param options
