hyprland-community/hyprland-rs

src/data/regular.rs

This add the missing `fullscreen` field for windows.

feat: add fullscreen field to window

---

src/dispatch.rs

Hi,
Thanks for this awesome lib. I start to use it, very good.
This add the renameworkspace dispatcher I recently add in hyprland.

feat: add renameworkspace dispatcher

---

MIGRATION.md
src/data/macros.rs
src/data/regular.rs
src/event_listener/mutable.rs
src/shared.rs

Make multiple item fetchers iterators

---

src/dispatch.rs

Hi !
This add the futur focus urgent or last window dispatcher, can be merge when this PR will be merge https://github.com/hyprwm/Hyprland/pull/1402

feat(dispatcher): add focus urgent or last window

---

src/ctl.rs
src/dispatch.rs
src/shared.rs

The code looks pretty like this. Its the shortest working with all case macro I was able to do. 🍒

chore: implement a macro for CommandContent

---

src/bin/example.rs
src/bin/example_async.rs
src/event_listener/async_im.rs
src/event_listener/immutable.rs
src/event_listener/mutable.rs
src/event_listener/shared.rs

using normal structs in this situation makes it much easier to know what are the fields and how to use them
c:

replace tuple structs with normal structs

---

src/data/regular.rs

They are announce since recently and usefull, I will start to use it on hyprland-autoname-workspaces for https://github.com/hyprland-community/hyprland-autoname-workspaces/issues/57

feat: this add the new `initialClass` and `initialTitle`

---

src/event_listener/async_im.rs
src/event_listener/async_mut.rs
src/event_listener/immutable.rs
src/event_listener/macros.rs
src/event_listener/mod.rs
src/event_listener/mutable.rs
src/event_listener/shared.rs

require: https://github.com/hyprwm/Hyprland/pull/2419

feat: add window title change event

---

Cargo.lock
Cargo.toml
README.md

nothing change, updating version everywhere

chore: release 0.3.6

---

src/event_listener/shared.rs

This make event handling less errors prone.
All credits to @MaximBaz

chore: refactoring to prevent bad event parsing using enum

---

src/data/regular.rs

fix: https://github.com/hyprland-community/hyprland-rs/issues/107

fix: monitor use u64

---

src/event_listener/async_im.rs
src/event_listener/immutable.rs
src/event_listener/macros.rs
src/event_listener/mutable.rs
src/event_listener/shared.rs

fix: https://github.com/hyprland-community/hyprland-rs/issues/109

chore: add workspace rename event

---

src/data/regular.rs

Not sure about the 1st, tho, I just haven't found a straightforward way to access them.

Make `Animations`' fields public, add 2 new animation styles

---

src/data/regular.rs

Maybe the documentation comment could be improved

Add support for https://github.com/hyprwm/Hyprland/issues/3661

---

src/data/regular.rs
src/shared.rs

fixes #124 (Client::get_active() doesn't work)

fixed get_active for client

---

src/data/regular.rs
src/event_listener/async_im.rs
src/event_listener/immutable.rs
src/event_listener/macros.rs
src/event_listener/mutable.rs
src/event_listener/shared.rs
src/keyword.rs

Solves (maybe partially) the issue #33.

refactor: reduced a bunch of .clone() functions

---

.gitignore
src/data/macros.rs
src/data/regular.rs
src/event_listener/async_im.rs
src/event_listener/mutable.rs
src/event_listener/shared.rs

The name `WorkspaceRuleset` is not final, but I couldn't think of anything else.

feat: workspacerules

---

src/dispatch.rs

Fixes `MoveCursorToCorner` behavior issue (#213). Updated values are sourced from https://wiki.hyprland.org/Configuring/Dispatchers/.

Correct Corner enum values

---

src/data/regular.rs

To support hyprwm/Hyprland#7104 changes in `Client`.

Support new fullscreen state in `Client`

---

src/data/regular.rs

@yavko could you publish a new alpha version on crates.io so that I could use the new changes and dogfood hyprswitch to test them?

fix: update Version Struct to contain all fields

---

src/data/regular.rs

This PR add the current active special workspace to the Monitor struct

Add special workspace to monitor

---

src/data/regular.rs

extend Version struct with version field

---

src/dispatch.rs

feat: added AlterZOrder dispatcher
